inventory:
  filename: ["images", "inventory.csv"]
  key: "image"
  fields: ["image", "age_approx", "anatom_site_general", "sex", "angle", "drawn"]
images:
  location: ["images"]
  ext: ".png"
  rows: 224
  columns: 224
  channels: 3
  rotations: [0, 90, 180, 270]
modelling:
  random_state: 5
  minimum_class_instances: 2
  batch_size: 32
  train_size_inventory: 0.70
  train_size_evaluation: 0.35
