name: derma
channels:
  - conda-forge
  - defaults
dependencies:
  - mxnet=1.2.1
  - pandas=0.25.2
  - matplotlib=3.1.1
  - setuptools=41.6.0
  - pytest=5.2.2
  - coverage=4.5.4
  - scikit-learn=0.20.1
  - requests=2.18.4
  - jupyterlab=1.2.3